DATA_DIR = '/home/guy/data/minimal_videos/clips/'
NEGATIVES_DIR = '/shared-data5/guy/data/minimal/negatives_video/'
SELECTIVE_SEARCH_DIR = '/home/guy/libs/selective_search/'
VOC_DIR = '/shared-data4/guy/data/VOC2012/'
UCF_DIR = '/shared-data5/guy/data/UCF-101/'